#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
IFS=$'\n\t'
set -euxo pipefail

EVENT=$1
case $EVENT in
  online)
    MSG="UPS is back online"
    ;;
  onbatt)
    MSG="UPS is on battery"
    ;;
  lowbatt)
    MSG="UPS is on battery and has a low battery (is critical)"
    ;;
  fsd)
    MSG="UPS is being shutdown by the primary (FSD = Forced Shutdown)"
    ;;
  commok)
    MSG="Communications established with the UPS"
    ;;
  commbad)
    MSG="Communications lost to the UPS"
    ;;
  shutdown)
    MSG="The system is being shutdown"
    ;;
  replbatt)
    MSG="The UPS battery is bad and needs to be replaced"
    ;;
  nocomm)
    MSG="A UPS is unavailable (can't be contacted for monitoring)"
    ;;
  noparent)
    MSG="upsmon parent process died - shutdown impossible"
    ;;
  *)
    echo "unexpected event $EVENT"
    exit 1
    ;;
esac

UPS=eaton@localhost
STAT=`upsc $UPS ups.status`
BATT=`upsc $UPS battery.charge`
RUNTIME=`upsc $UPS battery.runtime`
DATE=`date --iso-8601=seconds`
HOSTNAME=`hostname`

echo "$MSG\n\nDate: $DATE\nStatus: $STAT\nBattery charge: $BATT\nRuntime: $RUNTIME" | mail -s "UPS event $EVENT on $HOSTNAME" root
