parsers:
  - name: authelia_json
    format: json

pipeline:
  filters:
    - name: parser
      match: svc.authelia.service
      key_name: MESSAGE
      parser: authelia_json
      reserve_data: true
    - name: modify
      match: svc.authelia.service
      condition:
        - key_exists CONTAINER_TAG
        - key_exists msg
        - key_exists level
      hard_rename:
        - msg log
        - level _level
      remove: time
      set: parser_status parsed
