udm_syslog_listen_address: "{{ ansible_default_ipv4.address | mandatory }}"
udm_syslog_allowed_sources:
  - "{{ external_ips.udm }}"
  - "{{ network.static_leases.unifi_uap_iw_hd.ip }}"
  - "{{ network.static_leases.unifi_usw_8p.ip }}"
  - "{{ network.static_leases.unifi_usw_24_poe_gen2.ip }}"
  - "{{ network.static_leases.unifi_ap_nano_hd.ip }}"
udm_syslog_rate_limit_interval: 60
udm_syslog_rate_limit_burst: 20000
udm_syslog_logrotate_size: 100M
