#!/bin/bash

modprobe vfio-pci

for dev in "$@"; do
  if lspci -k -s $dev | grep -lq vfio-pci ; then
    echo "$dev already bound, skipping..."
    continue
  fi
  vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
  device=$(cat /sys/bus/pci/devices/$dev/device)
  if [ -e /sys/bus/pci/devices/$dev/driver ]; then
    echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
  fi
  echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id
  group=$(iommu_group_for_device $dev)
  chown libvirt-qemu:kvm /dev/vfio/$group
done
