parsers:
  - name: transmission_console
    format: regex
    regex: '/\A\[[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}(?:Z|[+-][0-9]{4})\] (?<transmission_level>TRC|DBG|INF|WRN|ERR|FTL) (?<transmission_source>[^:[:space:]]+):(?<transmission_source_line>[0-9]+) (?<transmission_message>[\s\S]*?) \([^:()]+:[0-9]+\)[[:space:]]*\z/'
    types: transmission_source_line:integer

pipeline:
  filters:
    - name: modify
      match: svc.transmission.service
      condition: key_exists CONTAINER_TAG
      rename: MESSAGE log
    - name: parser
      match: svc.transmission.service
      key_name: log
      parser: transmission_console
      reserve_data: true
      preserve_key: true
    - name: modify
      match: svc.transmission.service
      condition:
        - key_exists CONTAINER_TAG
        - key_exists transmission_message
        - key_exists transmission_level
      hard_rename:
        - transmission_message log
        - transmission_level _level
        - transmission_source source
        - transmission_source_line source_line
      set: parser_status parsed
