- name: _verify | Assert /etc/fan2go/fan2go.yaml is absent (disabled)
  when: not fan2go_enabled
  stat:
    path: /etc/fan2go/fan2go.yaml
  register: fan2go_config_absent
  failed_when: fan2go_config_absent.stat.exists

- name: _verify | Assert fan2go service unit is absent (disabled)
  when: not fan2go_enabled
  stat:
    path: /etc/systemd/system/fan2go.service
  register: fan2go_unit_stat_verify
  failed_when: fan2go_unit_stat_verify.stat.exists
