- name: Configure NodeSource apt repository
  import_role:
    name: apt_source
    tasks_from: configure
  vars:
    apt_source_args:
      name: nodesource
      key_id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4
      key_url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
      uris: "{{ mirror_apt_nodesource }}"
      suites: nodistro
      components: main
      pin:
        package: nodejs
        version: "{{ nodejs_major }}.*"
        priority: 600
  tags:
    - nodejs

- name: Install node
  when: not (ansible_check_mode and apt_source_nodesource_changed)
  apt:
    pkg:
      - nodejs
    cache_valid_time: 3600
  become: true
  tags:
    - nodejs
