parsers:
  - name: jellyfin_clef
    format: json

pipeline:
  filters:
    - name: parser
      match: svc.jellyfin.service
      key_name: MESSAGE
      parser: jellyfin_clef
      reserve_data: true
    - name: modify
      match: svc.jellyfin.service
      condition:
        - key_exists CONTAINER_TAG
        - key_value_equals JellyfinFormat clef
        - key_exists '@m'
      hard_rename: '@m log'
      rename:
        - SourceContext source
        - ThreadId thread_id
        - '@x exception'
        - '@tr trace_id'
        - '@sp span_id'
        - '@i event_id'
      remove:
        - '@t'
        - '@mt'
        - '@r'
        - JellyfinFormat
      add:
        - _level Information
    - name: modify
      match: svc.jellyfin.service
      condition: key_exists '@l'
      hard_rename: '@l _level'
