parsers:
  - name: sonarr_console
    format: regex
    regex: '/\A\[(?<_level>Trace|Debug|Info|Warn|Error|Fatal)\] (?<source>[^:]+): (?<log>[^\r\n]*?)[ \t]*(?:\r?\n(?:[[:space:]]*\r?\n)*\[v(?<app_version>[^]]+)\] (?<exception>[\s\S]*?))?[[:space:]]*\z/'

pipeline:
  filters:
    - name: parser
      match: svc.sonarr.service
      key_name: MESSAGE
      parser: sonarr_console
      reserve_data: true
