- name: _setup | Install podman
  import_role:
    name: podman
    tasks_from: install

- name: _setup | Install nginx
  import_role:
    name: test
    tasks_from: nginx

- name: _setup | Install authelia stub for auth=required tests
  import_role:
    name: test
    tasks_from: authelia_stub
  vars:
    authelia_stub_mode: gate
