- name: Install speedtest service
  import_role:
    name: systemd_unit
    tasks_from: install
  vars:
    systemd_unit_args:
      src: speedtest.service.j2
  tags:
    - speedtest

- name: Enable speedtest service
  import_role:
    name: systemd_unit
    tasks_from: service
  vars:
    systemd_unit_args:
      src: speedtest
      condition: "{{ not (ansible_check_mode and speedtest_service_result.changed) }}"
      restart: "{{ speedtest_service_result.changed }}"
  tags:
    - speedtest

- name: Configure nginx
  import_role:
    name: nginx
    tasks_from: site
  vars:
    nginx_site_args:
      subdomain: speedtest
      proxy_pass: http://127.0.0.1:2807/
      auth: required
  tags:
    - speedtest
