parsers:
  - name: bazarr_console
    format: regex
    regex: '^(?<bazarr_time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}) - (?<logger>[[:alnum:]_.-]+)[[:space:]]+\((?<thread_id>[0-9a-f]+)\) :[[:space:]]+(?<bazarr_level>[A-Z]+) \((?<source>[[:alnum:]_.-]+):(?<source_line>[0-9]+)\) - (?<message>.*)$'
    types: source_line:integer

pipeline:
  filters:
    - name: modify
      match: svc.bazarr.service
      rename: MESSAGE log
    - name: parser
      match: svc.bazarr.service
      key_name: log
      parser: bazarr_console
      reserve_data: true
      preserve_key: true
    - name: lua
      match: svc.bazarr.service
      script: /etc/fluent-bit/bazarr_normalize.lua
      call: normalize_bazarr
