- name: Add media group
  import_role:
    name: media
    tasks_from: group
  tags:
    - bazarr

- name: Set up bazarr system user, group, and config dir
  import_role:
    name: service_user
    tasks_from: user
  vars:
    service_user_args:
      name: bazarr
      extra_groups: [media]
  tags:
    - bazarr

- name: Create sqlite directory
  when: not (ansible_check_mode and bazarr_user.changed)
  file:
    dest: /mnt/services/sqlite/bazarr
    state: directory
    owner: bazarr
    group: media
    mode: "0755"
  become: true
  tags:
    - bazarr

- name: Create bazarr config subdirectory
  when: not (ansible_check_mode and bazarr_user.changed)
  file:
    dest: /mnt/services/bazarr/config
    state: directory
    owner: bazarr
    group: media
    mode: "0755"
  become: true
  tags:
    - bazarr

- name: Configure bazarr
  template:
    src: config.yaml.j2
    dest: /mnt/services/bazarr/config/config.yaml
    owner: bazarr
    group: media
    mode: "0600"
    backup: true
  register: bazarr_conf
  become: true
  tags:
    - bazarr

- name: Install bazarr service
  import_role:
    name: systemd_unit
    tasks_from: install
  vars:
    systemd_unit_args:
      src: bazarr.service.j2
      condition: "{{ not (ansible_check_mode and bazarr_user.changed) }}"
  tags:
    - bazarr

- name: Enable bazarr service
  import_role:
    name: systemd_unit
    tasks_from: service
  vars:
    systemd_unit_args:
      src: bazarr
      condition: "{{ not (ansible_check_mode and (bazarr_service_result.changed or bazarr_user.changed)) }}"
      restart: "{{ bazarr_service_result.changed or bazarr_conf.changed }}"
  tags:
    - bazarr

- name: Configure nginx
  import_role:
    name: nginx
    tasks_from: site
  vars:
    nginx_site_args:
      subdomain: bazarr
      proxy_pass: http://localhost:{{ service_ports.bazarr }}/
  tags:
    - bazarr
