- name: Copy sort_ini
  copy:
    src: sort_ini.py
    dest: /usr/local/bin/sort_ini
    owner: root
    group: root
    mode: "0755"
    backup: true
    validate: python3 -m py_compile "%s"
  become: true
  tags:
    - sort_ini
