netdata_keepalived_vrrp_enabled: "{{ (dns_keepalived_priority | default(0) | int) > 0 }}"
netdata_keepalived_lost_master_alert: >-
  {{ (dns_keepalived_priority | default(0) | int)
     == (dns_keepalived_priorities.values() | max) }}
netdata_zfspool_thresholds: {}
netdata_diskspace_blocklist: []
netdata_expected_charts: >-
  {{
    {
      'wireguard_bunk_peer':
        'wireguard.peer_wg0_'
        ~ wireguard_keys['bunk']['public_key']
        ~ '_latest_handshake_ago'
    }
    if inventory_hostname in wireguard_peers.get('bunk', {}).get('keepalive_from', [])
    else {}
  }}
