- name: _test | Install nginx
  import_role:
    name: _test
    tasks_from: nginx

- name: _setup | Install podman
  import_role:
    name: podman
    tasks_from: install

- name: _test | Setup dependencies
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /mnt/services
    - /mnt/scratch
    - /mnt/media
  become: true

- name: _test | Stub sort_ini binary
  file:
    src: /usr/bin/tail
    dest: /usr/local/bin/sort_ini
    state: link
  become: true
