- name: _setup | Install nginx
  import_role:
    name: nginx
    tasks_from: test_fixture

- name: _setup | Install fluent-bit for structured-log integration
  import_role:
    name: fluentbit
    tasks_from: configure
