zfs_root: false
home_subnet: 10.0.2.0/24
macvlan_parent: "{{ ansible_facts.interfaces | select('match', '^en') | sort | first }}"
grub_bootloader: true
netplan:
  ethernets:
    en:
      match:
        name: "en*"
      link-local: [] # do not setup random link local address when no dhcp is present
      wakeonlan: true
      dhcp4: true
      dhcp6: false

has_transcoding_acceleration: false
