gitea_version: "1.21.11"
gitea_release:
  x86_64:
    url: "{{ mirror_gitea_dl }}/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
    sha256: "238056fa4616633a9ec5a358aac75275bd3f271d5e5238af3dd5f22c713fe97e"
  aarch64:
    url: "{{ mirror_gitea_dl }}/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-arm64"
    sha256: "1bdbb3507067b3db9c2178be0bc038c2549fddb4eafff96d4a7c0010c7d1e404"
