- name: _setup | Install podman
  import_role:
    name: podman
    tasks_from: install

- name: _setup | Create media podman network
  import_role:
    name: media
    tasks_from: network

- name: _setup | Install nginx
  import_role:
    name: _test
    tasks_from: nginx

- name: _setup | Setup dependencies
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /mnt/services
    - /mnt/scratch
    - /mnt/media
  become: true

- name: _setup | Fake HW transcoding fixture (no GPU in QEMU)
  import_role:
    name: _test
    tasks_from: fake_render_device
