- name: Configure services datasets
  include_tasks:
    file: _dataset.yml
    apply:
      tags:
        - services
  loop: "{{ services_datasets }}"
  loop_control:
    label: "{{ item.dataset }}"
  tags:
    - services
